


--encontrar um cliente aleatório
DECLARE @CPF VARCHAR(MAX)
DECLARE @NUM_DE_CLIENTES INT
DECLARE @CONTADOR INT SET @CONTADOR = 1

	SELECT @NUM_DE_CLIENTES = COUNT(*) FROM [TABELA DE CLIENTES]

DECLARE @ALEATORIO INT
	SELECT @ALEATORIO = [dbo].[NUMEROALEATORIO](1, @NUM_DE_CLIENTES)

DECLARE CURSOR6 CURSOR FOR
	SELECT CPF FROM [TABELA DE CLIENTES]
OPEN CURSOR6 
	WHILE @CONTADOR <= @ALEATORIO
		BEGIN
			FETCH NEXT FROM CURSOR6 INTO @CPF	
		--	PRINT @CPF
			SET @CONTADOR = @CONTADOR + 1;
		END
CLOSE CURSOR6
DEALLOCATE CURSOR6

--SELECT @CPF


-- localizar vendedor aleatorio

DECLARE @MATRICULA VARCHAR(MAX)
DECLARE @NUM_DE_VENDEDORES INT
DECLARE @CONTADORVENDOR INT
	SET @CONTADORVENDOR = 0

	SELECT @NUM_DE_VENDEDORES = COUNT(*) FROM [TABELA DE VENDEDORES]

DECLARE @ALEATORIOVENDOR INT
	SET @ALEATORIOVENDOR = [dbo].[NUMEROALEATORIO](1,@NUM_DE_VENDEDORES)

DECLARE CURSOR7 CURSOR FOR
	SELECT MATRICULA FROM [TABELA DE VENDEDORES]
OPEN CURSOR7 
	WHILE @CONTADORVENDOR <= @ALEATORIOVENDOR
		BEGIN
			FETCH NEXT FROM CURSOR7 INTO @MATRICULA	
		--	PRINT @CPF
			SET @CONTADORVENDOR = @CONTADORVENDOR + 1;
		END
CLOSE CURSOR7
DEALLOCATE CURSOR7

--SELECT @MATRICULA

--localizando produto aleatorio

DECLARE CURSOR8 CURSOR FOR
	SELECT [CODIGO DO PRODUTO] FROM [TABELA DE PRODUTOS]

DECLARE @CODIGOPROD VARCHAR(MAX)
DECLARE @CONTADORPROD INT
	SET @CONTADORPROD = 0

DECLARE @TOTALPROD INT
	SET @TOTALPROD = (SELECT COUNT(*) FROM [TABELA DE PRODUTOS])

DECLARE @ALEATORIOPROD INT
	SET @ALEATORIOPROD = [dbo].[NUMEROALEATORIO](1, @TOTALPROD)

OPEN CURSOR8
	WHILE @CONTADORPROD < @ALEATORIOPROD
	BEGIN
		FETCH NEXT FROM CURSOR8 INTO @CODIGOPROD
		SET @CONTADORPROD += 1
	END
CLOSE CURSOR8
DEALLOCATE CURSOR8

SELECT @CODIGOPROD