
DECLARE @QUANTIDADE INT
DECLARE @PRECO FLOAT
DECLARE @FATURAMENTO FLOAT

DECLARE CURSOR5 CURSOR FOR
	SELECT I.[QUANTIDADE] , I.[PREÇO] FROM
		[ITENS NOTAS FISCAIS] I INNER JOIN [NOTAS FISCAIS] N 
		ON (N.NUMERO = I.NUMERO) WHERE DATA = '2015-01-01'
SET @FATURAMENTO = 0
OPEN CURSOR5
FETCH NEXT FROM CURSOR5 INTO @QUANTIDADE , @PRECO 
	WHILE @@FETCH_STATUS = 0
	BEGIN
	SET @FATURAMENTO = @FATURAMENTO  + ( @QUANTIDADE * @PRECO);
		FETCH NEXT FROM CURSOR5 INTO @QUANTIDADE , @PRECO;
		
		
	END
	SELECT  @FATURAMENTO
CLOSE CURSOR5
DEALLOCATE CURSOR5
	PRINT @FATURAMENTO

	IF OBJECT_ID('tempdb..#AB') IS NOT NULL DROP TABLE #AB

SELECT 
	N.NUMERO,
	[PREÇO] * QUANTIDADE AS [TOTAL]
	INTO #AB
	FROM [ITENS NOTAS FISCAIS] I
INNER JOIN [NOTAS FISCAIS] N ON (N.NUMERO = I.NUMERO)
	WHERE [DATA] = '2015-01-01'

--SELECT (1512.63 +234.273 +804.737+528.528)

SELECT SUM (TOTAL) FROM #AB 


--SELECT * FROM [NOTAS FISCAIS]