


--encontrar um cliente aleatório
DECLARE @CPF VARCHAR(MAX)
DECLARE @NUM_DE_CLIENTES INT
DECLARE @CONTADOR INT SET @CONTADOR = 1

	SELECT @NUM_DE_CLIENTES = COUNT(*) FROM [TABELA DE CLIENTES]

DECLARE @ALEATORIO INT
	SELECT @ALEATORIO = [dbo].[NUMEROALEATORIO](1, @NUM_DE_CLIENTES)

DECLARE CURSOR6 CURSOR FOR
	SELECT CPF FROM [TABELA DE CLIENTES]
OPEN CURSOR6 
	WHILE @CONTADOR < @ALEATORIO
		BEGIN
			FETCH NEXT FROM CURSOR6 INTO @CPF	
		--	PRINT @CPF
			SET @CONTADOR = @CONTADOR + 1;
		END
CLOSE CURSOR6
DEALLOCATE CURSOR6

SELECT @CPF