

--ENDERECO COMPLETO DO CLIENTE
----https://cursos.alura.com.br/course/tsql-com-sql-server-2017
DECLARE @NOME VARCHAR(MAX)
DECLARE @BAIRRO VARCHAR(MAX)
DECLARE @ENDERECO1 VARCHAR(MAX)
DECLARE @CIDADE VARCHAR(MAX)
DECLARE @ESTADO VARCHAR(MAX)


DECLARE CURSOR3 CURSOR FOR
	SELECT 
	NOME,
		BAIRRO, 
		CIDADE, 
		ESTADO, 
		[ENDERECO 1]
	FROM [TABELA DE CLIENTES]
OPEN CURSOR3
FETCH NEXT FROM CURSOR3 INTO @NOME, @BAIRRO, @CIDADE, @ESTADO, @ENDERECO1
WHILE @@FETCH_STATUS = 0
	BEGIN 
		FETCH NEXT FROM CURSOR3 INTO @NOME, @BAIRRO, @CIDADE, @ESTADO, @ENDERECO1
		PRINT @NOME + ', '+ @BAIRRO + ', ' + @CIDADE + ', ' + @ESTADO + ', ' +  @ENDERECO1
	END
CLOSE CURSOR3
DEALLOCATE CURSOR3