

CREATE VIEW VW_GERARNUM	AS SELECT RAND() AS VALUE

--SELECT * FROM VW_GERARNUM

CREATE FUNCTION NUMEROALEATORIO(@VALINI INT, @VALMAXIMO INT) RETURNS INT
AS 
BEGIN
	DECLARE @FLOAT_ALEATORIO FLOAT
	SET @FLOAT_ALEATORIO = (SELECT VALUE FROM VW_GERARNUM)
	DECLARE @NUM_ALEATORIO INT
		SET @NUM_ALEATORIO =  ROUND(((@VALMAXIMO - @VALINI - 1) * @FLOAT_ALEATORIO + @VALINI),0)
	RETURN @NUM_ALEATORIO
END

select [dbo].[NUMEROALEATORIO](10,20)