--DROP FUNCTION GERARAENTIDADESALEATORIAS
CREATE FUNCTION GERARAENTIDADESALEATORIAS (@NOMEDAENTIDADE VARCHAR(12)) RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @TABELA TABLE (CODIGO VARCHAR(MAX))
	DECLARE @CODIGO VARCHAR(MAX)
		--SET @ENTIDADE_ALEATORIA = 'A'

		IF @NOMEDAENTIDADE = 'CLIENTE'
		BEGIN
			INSERT INTO @TABELA (CODIGO) SELECT CPF AS CODIGO FROM [TABELA DE CLIENTES]
		END
	
		IF @NOMEDAENTIDADE = 'PRODUTO'
		BEGIN
			INSERT INTO @TABELA (CODIGO) SELECT [CODIGO DO PRODUTO] AS CODIGO FROM [TABELA DE PRODUTOS]
		END

		IF @NOMEDAENTIDADE = 'VENDEDOR'
		BEGIN
			INSERT INTO @TABELA (CODIGO) SELECT MATRICULA AS CODIGO FROM [TABELA DE VENDEDORES]
		END

		DECLARE @CONTADOR INT
			SET @CONTADOR = 0

		DECLARE @TOTAL INT 
			SET @TOTAL =  (SELECT COUNT(*) FROM @TABELA)

		DECLARE @ALEATORIO INT
			SET  @ALEATORIO = [dbo].[NUMEROALEATORIO](1, @TOTAL)

			DECLARE @ENTIDADEALEATORIA VARCHAR(MAX)

		DECLARE CURSOR9 CURSOR FOR 
			SELECT CODIGO FROM @TABELA
		OPEN CURSOR9 
			FETCH NEXT FROM CURSOR9 INTO @ENTIDADEALEATORIA
			WHILE @CONTADOR <= @ALEATORIO
			BEGIN
				FETCH NEXT FROM CURSOR9 INTO @ENTIDADEALEATORIA
				SET @CONTADOR = @CONTADOR + 1;
			END
		CLOSE CURSOR9
		DEALLOCATE CURSOR9


	RETURN @ENTIDADEALEATORIA
END

--select 
--[dbo].[GERARAENTIDADESALEATORIAS]('PRODUTO') , 
--[dbo].[GERARAENTIDADESALEATORIAS]('CLIENTE'),
--[dbo].[GERARAENTIDADESALEATORIAS]('VENDEDOR')