


DECLARE @CLIENTE VARCHAR(MAX)
DECLARE @VENDEDOR VARCHAR(MAX)
DECLARE @PRODUTO VARCHAR(MAX)
DECLARE @NUMERO INT

	SET @CLIENTE = [dbo].[GERARAENTIDADESALEATORIAS]('CLIENTE')
	SET @VENDEDOR = [dbo].[GERARAENTIDADESALEATORIAS]('VENDEDOR')
	SET @PRODUTO = [dbo].[GERARAENTIDADESALEATORIAS]('PRODUTO')
	SELECT @NUMERO = MAX(NUMERO) FROM [NOTAS FISCAIS]


	