



DECLARE @CLIENTE VARCHAR(MAX)
DECLARE @VENDEDOR VARCHAR(MAX)
DECLARE @PRODUTO VARCHAR(MAX)
DECLARE @NUMERO INT
DECLARE @DATA DATE
DECLARE @IMPOSTO FLOAT
DECLARE @PRECO FLOAT
DECLARE @NUM_DE_ITENS INT
DECLARE @CONTADOR INT
	SET @CONTADOR = 1

DECLARE @TOTALDEITENS INTEGER
	SET @NUM_DE_ITENS = [dbo].[NUMEROALEATORIO](2,10) 

	WHILE @CONTADOR <= @NUM_DE_ITENS
		BEGIN
			SET @CLIENTE = [dbo].[GERARAENTIDADESALEATORIAS]('CLIENTE')
			SET @VENDEDOR = [dbo].[GERARAENTIDADESALEATORIAS]('VENDEDOR')
			SET @PRODUTO = [dbo].[GERARAENTIDADESALEATORIAS]('PRODUTO')
			SET @DATA = GETDATE()
			SET @IMPOSTO = 0.18
			SELECT @NUMERO = MAX(NUMERO)+1 FROM [NOTAS FISCAIS]
			SELECT @PRECO = [PREÇO DE LISTA]FROM [TABELA DE PRODUTOS] WHERE @PRODUTO = [CODIGO DO PRODUTO]
			SET @CONTADOR += 1;
		
		
		PRINT 'INICIO'
		SELECT @CLIENTE, @VENDEDOR, @NUMERO, @PRODUTO, @DATA, @IMPOSTO, @PRECO, @NUM_DE_ITENS

	
		
		END
	

