

--GERANDO NUMEROS ALEATORIOS COM A FUNCAO RAND()

--LIMITANDO OS NMEROS GERADOS:
--VALOR MAXIMO, VALOR MININO, DIMINUIDO DO VALOR MAXIMO
SELECT (10 -1 -1)* RAND()+1

--ARREDONDANDO
SELECT ROUND( (10 -1 -1)* RAND()+1,0)